# Generated by Django 4.2.7 on 2023-12-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_estudio_libros_viedeojuegos_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viedeojuegos',
            new_name='videojuegos',
        ),
    ]
