# Generated by Django 4.2.7 on 2023-12-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_viedeojuegos_videojuegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/posts'),
        ),
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/posts'),
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/posts'),
        ),
    ]
